sonar.projectKey=investment
sonar.projectName=Investment API
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/config/**,**/*Application.java
sonar.cpd.exclusions=**/*Request.java,**/*Response.java,**/*Status.java
