spring:
  application:
    name: investment
  datasource:
    url: jdbc:h2:mem:investment
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
